server:
  port: 8007
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
        same-site: none
spring:
  consumer:
    value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    url: jdbc:mysql://localhost:3307/tickup
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

#socket:
#  host: ${SOCKET_HOST:localhost}
#  port: ${SOCKET_PORT:8007}

